---
- name: Copy public key to remote host for users
  hosts: all
  gather_facts: false

  tasks:
    - name: Display instruction
      run_once: true
      debug:
        msg: "VARJAL TURELMESEN AMIG NEM VEGEZ, TOBB PERCIG IS ELTARTHAT!!!!!!!!!!!!!!!"
        
    - name: Ping host (this will create the home folder)
      become: true
      become_user: "{{ filename }}"
      ping:

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ filename }}"
        state: present
        key: "{{ lookup('file', '/{{ filepath }}/{{ filename }}') }}"