---
- name: Copy public key to remote host for users
  hosts: all
  gather_facts: false

  tasks:
    - name: Display username (which is equal to the given filename)
      debug:
        msg: "username: {{ filename }}"

    - name: Add the user with a bash shell (make sure that home folder is created)
      ansible.builtin.user:
        name: "{{ filename }}"
        shell: /bin/bash
        groups: students

    # - name: Ping host
    #   become: true
    #   become_user: {{ filename }}
    #   ping:

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ filename }}"
        state: present
        key: "{{ lookup('file', '/{{ filepath }}/{{ filename }}') }}"